# Part B - 
#   Amend the program so that the hidden number (between 1 and 20) is a random number 
#   generated by the program (check tutorial 3 Question 3 for how to generate a random number).

import random

hidden = random.randint(1, 20)
entered_num = int(input("Guess the number(Between 1 & 20)"))
if entered_num == hidden:
    print("Your guess was correct!")
else:
    while entered_num != hidden:
        print("Please guess again: ")
        entered_num = int(input("Guess the number(Between 1 & 20)"))
    print("Your guess was correct!")